<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241031165508 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE movie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, adult BOOLEAN DEFAULT NULL, original_title VARCHAR(255) DEFAULT NULL, overview TEXT DEFAULT NULL, popularity DOUBLE PRECISION DEFAULT NULL, release_date DATE DEFAULT NULL, vote_average DOUBLE PRECISION DEFAULT NULL, vote_count INT DEFAULT NULL, budget INT DEFAULT NULL, imdb_id VARCHAR(255) DEFAULT NULL, revenue INT DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, tagline VARCHAR(255) DEFAULT NULL, video BOOLEAN DEFAULT NULL, tmdb_id INT DEFAULT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE movie');
    }
}
