<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241101102404 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE movie_collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE movie ADD homepage VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD belongs_to_collection_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE movie ADD CONSTRAINT FK_1D5EF26F3C898583 FOREIGN KEY (belongs_to_collection_id) REFERENCES movie_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_1D5EF26F3C898583 ON movie (belongs_to_collection_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE movie_collection');
        $this->addSql('ALTER TABLE movie DROP CONSTRAINT FK_1D5EF26F3C898583');
        $this->addSql('DROP INDEX IDX_1D5EF26F3C898583');
        $this->addSql('ALTER TABLE movie DROP homepage');
        $this->addSql('ALTER TABLE movie DROP belongs_to_collection_id');
    }
}
