services:
    App\Service\TMDB\Manager\MovieManager:
        public: true
        autowire: true
        autoconfigure: true
    App\Service\TMDB\Manager\MovieGenreManager:
        public: true
        autowire: true
        autoconfigure: true
    App\Service\Minio\Client:
        public: true
        autowire: true
        autoconfigure: true
    App\Service\Minio\FileSystem:
        public: true
        autowire: true
        autoconfigure: true